(part "AL5809-20P1-7"
    (packageRef "AL580920QP17")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Diodes Inc.")
    (property "Manufacturer_Part_Number" "AL5809-20P1-7")
    (property "Mouser_Part_Number" "621-AL5809-20P1-7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/AL5809-20P1-7?qs=9BjnSzo86S%252BJEo7jKmhSEQ%3D%3D")
    (property "Arrow_Part_Number" "AL5809-20P1-7")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/al5809-20p1-7/diodes-incorporated")
    (property "Description" "LED Lighting Drivers LED HV Int Switch")
    (property "Datasheet_Link" "https://www.diodes.com/assets/Datasheets/AL5809.pdf")
    (property "symbolName1" "AL5809-20P1-7")
)
