(part "VEML7700-TR"
    (packageRef "VEML7700")
    (interface
        (port "1" (symbPinId 1) (portName "SCL") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VDD") (portType POWER))
        (port "3" (symbPinId 3) (portName "GND") (portType GROUND))
        (port "4" (symbPinId 4) (portName "SDA") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "VEML7700-TR")
    (property "Mouser_Part_Number" "78-VEML7700-TR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/VEML7700-TR?qs=BcfjnG7NVaWcZHs8m27pyQ%3D%3D")
    (property "Arrow_Part_Number" "VEML7700-TR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/veml7700-tr/vishay")
    (property "Description" "High Accuracy Ambient Light Sensor with I2C Interface")
    (property "Datasheet_Link" "http://www.vishay.com/docs/84286/veml7700.pdf")
    (property "symbolName1" "VEML7700-TR")
)
