PULSONIX_LIBRARY_ASCII "SamacSys ECAD Model"
//334605/255746/2.49/4/3/Integrated Circuit

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "r160_70"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 0.7) (shapeHeight 1.6))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(textStyleDef "Normal"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 1.27)
			(strokeWidth 0.127)
		)
	)
	(patternDef "VEML7700" (originalName "VEML7700")
		(multiLayer
			(pad (padNum 1) (padStyleRef r160_70) (pt 1.495, -0.4) (rotation 0))
			(pad (padNum 2) (padStyleRef r160_70) (pt 2.765, -0.4) (rotation 0))
			(pad (padNum 3) (padStyleRef r160_70) (pt 4.035, -0.4) (rotation 0))
			(pad (padNum 4) (padStyleRef r160_70) (pt 5.305, -0.4) (rotation 0))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt 3.08346, 1.75438) (textStyleRef "Normal") (isVisible True))
		)
		(layerContents (layerNumRef 28)
			(line (pt 0 3.2) (pt 6.8 3.2) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt 6.8 3.2) (pt 6.8 0) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt 6.8 0) (pt 0 0) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt 0 0) (pt 0 3.2) (width 0.025))
		)
		(layerContents (layerNumRef 18)
			(line (pt 0 3.2) (pt 6.8 3.2) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt 6.8 3.2) (pt 6.8 0) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt 0 3.2) (pt 0 0) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt 0 0) (pt 0.944 0) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt 6.8 0) (pt 5.92 0) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(arc (pt 0.61, -0.942) (radius 0) (width 0.2))
		)
	)
	(symbolDef "VEML7700-TR" (originalName "VEML7700-TR")

		(pin (pinNum 1) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -25 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 2) (pt 0 mils -100 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -125 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 3) (pt 0 mils -200 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -225 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 4) (pt 0 mils -300 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -325 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(line (pt 200 mils 100 mils) (pt 700 mils 100 mils) (width 6 mils))
		(line (pt 700 mils 100 mils) (pt 700 mils -400 mils) (width 6 mils))
		(line (pt 700 mils -400 mils) (pt 200 mils -400 mils) (width 6 mils))
		(line (pt 200 mils -400 mils) (pt 200 mils 100 mils) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 750 mils 300 mils) (justify Left) (isVisible True) (textStyleRef "Normal"))
		(attr "Type" "Type" (pt 750 mils 200 mils) (justify Left) (isVisible True) (textStyleRef "Normal"))

	)
	(compDef "VEML7700-TR" (originalName "VEML7700-TR") (compHeader (numPins 4) (numParts 1) (refDesPrefix IC)
		)
		(compPin "1" (pinName "SCL") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Unknown))
		(compPin "2" (pinName "VDD") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Power))
		(compPin "3" (pinName "GND") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Power))
		(compPin "4" (pinName "SDA") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Unknown))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "VEML7700-TR"))
		(attachedPattern (patternNum 1) (patternName "VEML7700")
			(numPads 4)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
				(padNum 3) (compPinRef "3")
				(padNum 4) (compPinRef "4")
			)
		)
		(attr "Manufacturer_Name" "Vishay")
		(attr "Manufacturer_Part_Number" "VEML7700-TR")
		(attr "Mouser Part Number" "78-VEML7700-TR")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/VEML7700-TR?qs=BcfjnG7NVaWcZHs8m27pyQ%3D%3D")
		(attr "Arrow Part Number" "VEML7700-TR")
		(attr "Arrow Price/Stock" "https://www.arrow.com/en/products/veml7700-tr/vishay")
		(attr "Description" "High Accuracy Ambient Light Sensor with I2C Interface")
		(attr "<Hyperlink>" "http://www.vishay.com/docs/84286/veml7700.pdf")
	)

)
