(part "TL760M33QKVURQ1"
    (packageRef "KVU-_R-PSFM-G3_")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OUTPUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_(TAB)") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TL760M33QKVURQ1")
    (property "Mouser_Part_Number" "595-TL760M33QKVURQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TL760M33QKVURQ1?qs=i6VRxKQL%2FYy73wExkuT1dg%3D%3D")
    (property "Arrow_Part_Number" "TL760M33QKVURQ1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tl760m33qkvurq1/texas-instruments")
    (property "Description" "Automotive Catalog Single Output LDO, 500mA, Fixed(3.3V), Load Dump Protection")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/tl760m33-q1.pdf")
    (property "symbolName1" "TL760M33QKVURQ1")
)
