PULSONIX_LIBRARY_ASCII "SamacSys ECAD Model"
//667316/255746/2.49/3/4/Integrated Circuit

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "r334_107"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 1.07) (shapeHeight 3.34))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(padStyleDef "r620_540"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 5.4) (shapeHeight 6.2))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(textStyleDef "Normal"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 1.27)
			(strokeWidth 0.127)
		)
	)
	(patternDef "KVU-(R-PSFM-G3)" (originalName "KVU-(R-PSFM-G3)")
		(multiLayer
			(pad (padNum 1) (padStyleRef r334_107) (pt -2.29, -2.947) (rotation 0))
			(pad (padNum 2) (padStyleRef r334_107) (pt 2.29, -2.947) (rotation 0))
			(pad (padNum 3) (padStyleRef r620_540) (pt 0, 4.453) (rotation 0))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt -0.432, -2.917) (textStyleRef "Normal") (isVisible True))
		)
		(layerContents (layerNumRef 28)
			(line (pt -3.3 6.22) (pt 3.3 6.22) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt 3.3 6.22) (pt 3.3 0) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt 3.3 0) (pt -3.3 0) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt -3.3 0) (pt -3.3 6.22) (width 0.025))
		)
		(layerContents (layerNumRef 18)
			(line (pt -3.3 6.22) (pt -3.3 0) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt -3.3 0) (pt 3.3 0) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt 3.3 0) (pt 3.3 6.22) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(arc (pt -3.647, -4.457) (radius 0) (width 0.2))
		)
	)
	(symbolDef "TL760M33QKVURQ1" (originalName "TL760M33QKVURQ1")

		(pin (pinNum 1) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -25 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 2) (pt 0 mils -100 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -125 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 3) (pt 1500 mils 0 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 1270 mils -25 mils) (rotation 0]) (justify "Right") (textStyleRef "Normal"))
		))
		(line (pt 200 mils 100 mils) (pt 1300 mils 100 mils) (width 6 mils))
		(line (pt 1300 mils 100 mils) (pt 1300 mils -200 mils) (width 6 mils))
		(line (pt 1300 mils -200 mils) (pt 200 mils -200 mils) (width 6 mils))
		(line (pt 200 mils -200 mils) (pt 200 mils 100 mils) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 1350 mils 300 mils) (justify Left) (isVisible True) (textStyleRef "Normal"))
		(attr "Type" "Type" (pt 1350 mils 200 mils) (justify Left) (isVisible True) (textStyleRef "Normal"))

	)
	(compDef "TL760M33QKVURQ1" (originalName "TL760M33QKVURQ1") (compHeader (numPins 3) (numParts 1) (refDesPrefix IC)
		)
		(compPin "1" (pinName "INPUT") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Unknown))
		(compPin "2" (pinName "OUTPUT") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Unknown))
		(compPin "3" (pinName "GND (TAB)") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Unknown))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "TL760M33QKVURQ1"))
		(attachedPattern (patternNum 1) (patternName "KVU-(R-PSFM-G3)")
			(numPads 3)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
				(padNum 3) (compPinRef "3")
			)
		)
		(attr "Manufacturer_Name" "Texas Instruments")
		(attr "Manufacturer_Part_Number" "TL760M33QKVURQ1")
		(attr "Mouser Part Number" "595-TL760M33QKVURQ1")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TL760M33QKVURQ1?qs=i6VRxKQL%2FYy73wExkuT1dg%3D%3D")
		(attr "Arrow Part Number" "TL760M33QKVURQ1")
		(attr "Arrow Price/Stock" "https://www.arrow.com/en/products/tl760m33qkvurq1/texas-instruments")
		(attr "Description" "Automotive Catalog Single Output LDO, 500mA, Fixed(3.3V), Load Dump Protection")
		(attr "<Hyperlink>" "http://www.ti.com/lit/ds/symlink/tl760m33-q1.pdf")
		(attr "<STEP Filename>" "TL760M33QKVURQ1.stp")
		(attr "<STEP Offsets>" "X=0;Y=0;Z=0")
		(attr "<STEP Rotation>" "X=0;Y=0;Z=0")
	)

)
