(part "GW12RCH"
    (packageRef "GW12RCH")
    (interface
        (port "4" (symbPinId 1) (portName "NO") (portType INOUT))
        (port "5" (symbPinId 2) (portName "COM") (portType INOUT))
        (port "6" (symbPinId 3) (portName "NC") (portType INOUT))
        (port "MH1" (symbPinId 4) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 5) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "NKK Switches")
    (property "Manufacturer_Part_Number" "GW12RCH")
    (property "Mouser_Part_Number" "633-GW12RCH")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/NKK-Switches/GW12RCH?qs=4EnmSMTL3HMGaO7owX5AXQ%3D%3D")
    (property "Arrow_Part_Number" "GW12RCH")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/gw12rch/nkk-switches")
    (property "Description" "Switch Rocker ON None ON SPDT PC Pins Curved Rocker 0.1A 28VAC 28VDC 0.4VA 50000Cycles")
    (property "Datasheet_Link" "https://www.mouser.com/datasheet/2/295/GW-1663576.pdf")
    (property "symbolName1" "GW12RCH")
)
