(part "TL2575HV-05IKV"
    (packageRef "TO170P470X1016X2338-5P")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OUTPUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "FEEDBACK") (portType INOUT))
        (port "5" (symbPinId 5) (portName "%ON%/OFF") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "37")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TL2575HV-05IKV")
    (property "Mouser_Part_Number" "595-TL2575HV-05IKV")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=595-TL2575HV-05IKV")
    (property "Arrow_Part_Number" "TL2575HV-05IKV")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tl2575hv-05ikv/texas-instruments?region=nac")
    (property "Description" "1-A Simple Step-Down Switching Voltage Regulators")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tl2575hv-05")
    (property "symbolName1" "TL2575HV-05IKV")
)
